/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ImageProcessor {
  width: number
  height: number
  constructor(width: number, height: number)
  processImage(frame: Uint8Array, threshold: number, kernelSize: number, dilateSize: number, minArea: number): Array<BoundingBox>
  reconfigure(width: number, height: number): void
  resetState(): void
  processImageDebug(frame: Uint8Array, threshold: number, kernelSize: number, dilateSize: number, minArea: number, outputDir: string, prefix: string): Array<BoundingBox>
}

export type BoundingBox =
  number[]
